### ISSUE TITLE
Explain what this fork brings to the table

### ISSUE THREAD

**Issue by judofyr** [sbtourist/Journal.IO#1]

**Comment by sbtourist** [comment]
The fork has been made mainly to allow for faster development and release cycles.

The current Journal.IO version provides the following new features which didn't get into HawtJournal:
1) Redesigned batching system.
2) Redesigned concurrency management.
3) Log compaction.
4) No external dependencies.
5) No OSGI support.

Does it answer your question?

**Comment by judofyr** [comment]
Yes! Maybe you should put it in the README?
