### ISSUE TITLE
java.io.IOException: Bad checksum for location on Journal.recoveryCheck

### ISSUE THREAD

**Issue by chrismongillo** [sbtourist/Journal.IO#11]
Hi Sergio,
during our first tests with your amazing Journal.IO we face this exception on journal reopening. After some analysis it seems the problem is not related with compact operation as we thought, but it occurs always at reopening after a previous delete. That's a simple test I did on the 1.1-snapshot

```

 @Test
    public void test_bad_checksum_issue_after_delete() throws IOException {
        Journal journal = new Journal();
        String basePath = this.getClass().getClassLoader().getResource(".").getFile();
        journal.setDirectory(new File(basePath));
        journal.setFilePrefix(UUID.randomUUID().toString());
        journal.open();
        journal.write(String.valueOf("bad checksum issue").getBytes(Charset.forName("UTF-8")), true);
        Iterator<Location> locationsIterator = journal.redo().iterator();
        while (locationsIterator.hasNext()) {
            Location location = locationsIterator.next();
            journal.delete(location);
        }
        journal.compact();
        journal.close();
        journal.open();

    }

```

**Comment by sbtourist** [comment]
Just found a bug affecting checksum verification for deleted records: to make a long story short, record type is currently part of the checksum, so when it changes after record deletion, checksum changes too as a consequence breaking the previously computed one.

Will look into and fix it in the next few days.

**Comment by sbtourist** [comment]
Should be fixed on master now: please give it a try and let me know.

**Comment by chrismongillo** [comment]
Yes Sergio it works fine ;) tnx!

**Comment by sbtourist** [comment]
Cool :)
