### ISSUE TITLE
Recovery Error Handler

### ISSUE THREAD

**Issue by sbtourist** [sbtourist/Journal.IO#14]
Currently, the recovery check process just aborts in case of checksum errors, preventing so to use a whole journal even if only a single error occurs.

We should introduce a recovery check error handler which will allow users to customise such a behaviour. Initial implementations would allow to either:
- Abort.
- Log and ignore.
- Mark bad locations as deleted and continue.

**Comment by krasserm** [comment]
Definitely a useful feature. Expect a pull request once I work on more fine-grained error handling in my app.

**Comment by sbtourist** [comment]
Cool.

I'll also try to find the time for a first implementation in the next few days, keep you posted.

**Comment by chrisvest** [comment]
What does the checksum cover? Can we trust that the location has been read correctly enough that we can mark it as deleted? If so, then it might be useful to pull data in from a possible ReplicationTarget (or whatever concrete thing it might represent) to repair the bad location.

**Comment by sbtourist** [comment]
That's a neat idea Chris, even if we don't currently have any APIs for that kind of behaviour on ReplicationTarget: any ideas about how to do that?

**Comment by chrisvest** [comment]
No, I haven't really thought much about the code or design part of this.

**Comment by sbtourist** [comment]
Pushed initial implementation at: https://github.com/sbtourist/Journal.IO/tree/wip-recovery

**Comment by sbtourist** [comment]
Implemented, see:
- journal.io.api.RecoveryErrorHandler
- journal.io.api.Journal#setRecoveryErrorHandler
