### ISSUE TITLE
NPE thrown when File#listFiles throws null

### ISSUE THREAD

**Issue by jeluard** [sbtourist/Journal.IO#34]
[File#listFiles](https://github.com/sbtourist/Journal.IO/blob/master/src/main/java/journal/io/api/Journal.java#L173) throwing null is not consistently handled and might throw a NPE. Fixing that in current codebase makes next #write call throw a FileNotFoundException (which is a good as before it failed silently).

Now I am wondering if an Exception should not be thrown before to ensure consistency (during open?).
Does it make sense to continue when File#listFiles returns null?

**Comment by sbtourist** [comment]
Right, an exception should definitely be thrown during open(), as listFiles() can only return null if the provided path does not exist or cannot be read.

Feeling like submitting a pull request for that? :)

**Comment by jeluard** [comment]
Sure I'll do that! Still fighting with git.

**Comment by jeluard** [comment]
Ok last one should be fine. Not sure how to clean all previous messages though (they belong to now deleted branches).
