### ISSUE TITLE
java.io.IOException: Invalid location when redoing a compacted journal

### ISSUE THREAD

**Issue by SebastianStoll** [sbtourist/Journal.IO#39]
Hej Hej, 

While testing this library I came across an issue when trying to redo a journal that was previously compacted. The used journal.io version is 1.3 .

Lets consider the following scenario:
- create a new journal instance with the following options 
  - journal.setArchiveFiles(false)
  - journal.setChecksum(true)
  - journal.setMaxFileLength(1024 \* 1024)
  - journal.setMaxWriteBatchSize(1024 \* 10)
- write an arbitrary amount of data to the journal using WriteType.SYNC
- redo the journal and delete all listed locations
- write more data
- compact the journal
- close and reopen the journal
- redo the journal

which will cause the following exception eg:

```
Invalid location: 1:13987:1, found: null
    java.io.IOException: Invalid location: 1:13987:1, found: null    
    at journal.io.api.DataFileAccessor.readLocation(DataFileAccessor.java:97)
    at journal.io.api.Journal.read(Journal.java:301)
```

It seems that the compaction of journal db files with some but not all locations marked as deleted causes an invalid journal state. Further redos/reads will cause the error above. 

I noticed though that a new instance of the journal using the same journal db files is able to redo/read locations.

Is the depicted behaviour a bug or simply a use case that is not supported?

Best,
Sebastian

**Comment by sbtourist** [comment]
Thanks for the report Sebastian.

This is most certainly a bug: could you please attach a simple test case reproducing it, so I can have a deeper look?

**Comment by sbtourist** [comment]
Fixed, have a try :)

**Comment by SebastianStoll** [comment]
Works perfectly and thank you for fixing that so quickly!

**Comment by sbtourist** [comment]
Glad to know :)

I'll hopefully release a new version with this fix (and some others) in the next few weeks, feel free to join the mailing list to watch out for announcements.
