### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by brianm** [sbtourist/Journal.IO#7]
Could you publish releases to maven central? Relying on a custom repo makes it difficult to depend on for other libraries -- all of the dependent libraries users need to configure the custom repo as well.

**Comment by sbtourist** [comment]
I'll try to do that ASAP.

**Comment by sbtourist** [comment]
@brianm, can we close this one?

**Comment by brianm** [comment]
By all means :-)

**Comment by brianm** [comment]
Though I would love if you could push a release to maven central!

**Comment by sbtourist** [comment]
Isn't the sonatype repo synced with maven central already?

**Comment by brianm** [comment]
Yep, so cut a release!

**Comment by sbtourist** [comment]
You'll have to wait a few weeks for 1.3 :)

**Comment by sbtourist** [comment]
@brianm, I uploaded a snapshot to Sonatype.
It may well be a candidate for the final 1.3 version, that I plan to release during the coming week, so check it out if you'd like to have a look at performance improvements and bug fixes.

**Comment by sbtourist** [comment]
Closed, as deployed on Sonatype.
